### ISSUE TITLE
What is the install procedure when on Windows?

### ISSUE THREAD

**Issue by guyinpv** [flyntwp/flynt#129]
I am trying to use this on a dev project but I've tried 4 different times in different ways to install it and it doesn't work.

The instructions say to run `composer install`, that works.
Then it says to run `npm install`, this works, though it the audit complains about a lot of packages.

It's running `npm run build` that won't work. I get multiple of these:
```
npm ERR! code ELIFECYCLE
```

Part of the issue is that the build command doesn't use a syntax that Windows can use. For example it can't just run `NODE_ENV=production....`. You have to use the `set` command for environment vars.
And then it uses a variable `$npm_execpath` which doesn't do anything.
It runs `gulp` command but that doesn't seem to be installed by npm? I had to install that globally for it to work like this.

The linter commands fail. 

I've tried this 3 times with fresh clones from Git in different paths on my computer, using two tools (AMPPS, and Local by Flywheel), neither worked. Flywheel was the worst, npm install didn't even work, it had a lot of permissions errors.

Then I downloaded a live/working version of a Flynt theme and ran npm install on it, then tried to run build and it still didn't work.

I'm not sure what else to try and fix! I tried to do `npm update` just to see if updating packages across the board would work, and it didn't.

Here is the output in my CLI:
```
D:\www\www\temp-site\wp-content\themes\test-theme  (flynt@1.0.0-rc1)
$ npm run build
> flynt@1.0.0-rc1 build D:\www\www\temp-site\wp-content\themes\test-theme
> check-node-version --package -p && npm run clean && set NODE_ENV=production webpack --progress --display=minimal && gulp rev

node: 10.16.0
npm: 6.10.2
npx: 6.10.2
yarn: 1.17.3

> flynt@1.0.0-rc1 clean D:\www\www\temp-site\wp-content\themes\test-theme
> rm -rf ./dist

[16:34:05] Using gulpfile D:\www\www\temp-site\wp-content\themes\test-theme\gulpfile.js
[16:34:05] Starting 'rev'...
[16:34:05] Starting 'revAssets'...
[16:34:05] Finished 'revAssets' after 122 ms
[16:34:05] Starting 'revUpdateReferences'...
[16:34:05] 'revUpdateReferences' errored after 15 ms
[16:34:05] Error: File not found with singular glob: D:/www/www/temp-site/wp-content/themes/test-theme/dist\rev-manifest.json (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (D:\www\www\temp-site\wp-content\themes\test-theme\node_modules\glob-stream\readable.js:84:17)
    at Object.onceWrapper (events.js:286:20)
    at Glob.emit (events.js:198:13)
    at Glob.EventEmitter.emit (domain.js:448:20)
    at Glob._finish (D:\www\www\temp-site\wp-content\themes\test-theme\node_modules\glob\glob.js:197:8)
    at done (D:\www\www\temp-site\wp-content\themes\test-theme\node_modules\glob\glob.js:182:14)
    at Glob._processSimple2 (D:\www\www\temp-site\wp-content\themes\test-theme\node_modules\glob\glob.js:688:12)
    at D:\www\www\temp-site\wp-content\themes\test-theme\node_modules\glob\glob.js:676:10
    at Glob._stat2 (D:\www\www\temp-site\wp-content\themes\test-theme\node_modules\glob\glob.js:772:12)
    at lstatcb_ (D:\www\www\temp-site\wp-content\themes\test-theme\node_modules\glob\glob.js:764:12)
[16:34:05] 'rev' errored after 144 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flynt@1.0.0-rc1 build: `check-node-version --package -p && npm run clean && set NODE_ENV=production webpack --progress --display=minimal && gulp rev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the flynt@1.0.0-rc1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vigil\AppData\Roaming\npm-cache\_logs\2019-09-11T23_34_05_389Z-debug.log

D:\www\www\temp-site\wp-content\themes\test-theme  (flynt@1.0.0-rc1)
```

You'll notice I changed the build commands to at least try to get them working on Windows, but it still fails with the `gulp rev` stuff it seems like.

I don't know what else to try.

Thanks for any help

**Comment by domtra** [comment]
Sorry for the trouble you are going through. Unfortunately we haven't done any specific preparation to ensure that flynt is running well on Windows. 
We will have a look at your issues once we can get a Windows machine set up and see what we can do to fix them. Until then, there is not a lot I can help you with.
local by flywheel should work, however. This uses docker underneath, so you will get a linux system to work with. The important part is not to run the command in your windows environment but first to connect to the docker container and execute everything in there. 
Maybe this helps. For the rest, I will keep you updated once we have had a look at the issues.

**Comment by bdbch** [comment]
@guyinpv I'd suggest you try to use WSL until crossplatform support is available, works fine for me for 99% of the time.

**Comment by bdbch** [comment]
Also there was an issue with WSL and MySQL when you have your servers running on windows but use WSL as the tooling shell. For me the best fix was always to set the MySQL client protocol to TCP:

https://github.com/microsoft/WSL/issues/745#issuecomment-327301645

**Comment by guyinpv** [comment]
I have a few notes for getting it working in Windows.

At the least, I had to do these:

1. Find references to "gulp.src" and add this as an option in all 6 references: "{allowEmpty: true}"
This avoids glob errors in `run build`.
2. Adjust all the commands in package.json to be Windows style. No "$npm" variables for path. Change the "rm" bash command to `rd /Q /s dist || rem` instead.
3. Remove lint command since it creates a ton of issues by itself. I didn't bother trying to fix all the issues with linter.
4. Add the "set" keyword before setting any environment variables.

The `npm run build` command worked at this point and I could run `npm start` to watch files.

I haven't tried WSL  but I'm sure that would be one technique I guess.

**Comment by domtra** [comment]
Hi @guyinpv, hi @bdbch,
we have fixed all the issues we could find when running the npm commands on windows.
The only issue that is left is line ending on windows. This totally depends on how you configure git to work on you machine.
We would appreciate any sort of feedback if v1.0.0 is working for you or if you still experience any issues.
Cheers.

**Comment by papsko** [comment]
Hi @guyinpv, HI @domtra,

What a timing! We now want to give a shot to flynt in our projects and my colleague who tried to install it on windows couple days ago also fell in lots of trouble!

I've just downloaded v1.0.0 and installed it on my windows 10 machine. All comands have sucessfully run with git bash. No fatal errors. Everything works just fine ;D. 

Thank you very much for the update!
