### ISSUE TITLE
Using FlyntWP with Gatsby

### ISSUE THREAD

**Issue by bdbch** [flyntwp/flynt#131]
Heyho. I recently fell in love with GatsbyJS and would love to try Flynt out in combination with Gatsby to create static websites. Did you ever had a thought on that or have an idea how this could be implemented with the current Flynt stack?

Is there a way to get page components via the WPJSON API or do we need to make adjustments to make FlyntWP headless compatible?

**Comment by domtra** [comment]
Hi @bdbch, 
thanks for you question. Are also really like what gatsby is doing. 
However, gatsby support is nothing we will implement in the theme. flynt brings along its own build process, twig templates and much more. For a gatsby site, you would not need any of this.
To me, using ACF Field Group Composer ins a plugin or bare bone theme would probably do the trick. This way you can define field groups, etc, manage content via wp-admin and use is in gatsby to create static pages. You would have to create some logic on how to load components on a page and then render those react components via gatsby.
To get better support for acf and better performance for wordpress queries, you should not use the default gatsby wordpress source plugin, but rather wpgraphql. there is even an [acf extension](https://www.wpgraphql.com/acf/).
additionally there are a couple of projects that want to help joining wp and gatsby together. one is https://staticfuse.com/, but i haven't really looked into this.
hope this answer can help you.
