### ISSUE TITLE
Optional Gutenberg support

### ISSUE THREAD

**Issue by bdbch** [flyntwp/flynt#17]
Hey FlyntWP / bleech team! Hope everything is fine!

For the last 4 days I played around with the new ACF Pro Gutenberg Blocks in ACF Pro 5.8 and I think it's now way easier to register Flynt components into Gutenberg and also load necessary style and javascript files for the admin area.

I worked on a prototype and got dynamic component registration working for Gutenberg outside of the Flynt ecosystem. I started to implement optional Gutenberg component registration and Component rendering into the Flynt theme yesterday and look forward to send a pull request very soon.

Are you already working on something similar?

My current state looks as following:

1. Implemented a `useGutenberg` protected static variable in the `Defaults` class
2. Added the useGutenberg static function to update the protected variable
3. Added `useGutenberg(false)` into the Init.php
4. Added a check for the useGutenberg variable in the RemoveEditor.php file (If set to true, the default editor will be loaded with Gutenberg activated)
5. Disabled Component Registration via ACF layouts in the API class when useGutenberg is true

Now I'm working on the registration via [acf_register_block_type()](https://www.advancedcustomfields.com/resources/acf_register_block_type/) and updating the renderer to use the_content() if Gutenberg is enabled instead of the dynamic renderer via the ACF layout field.

Obviously there are some differences and incompatibilities with the ACF layout approach and the Gutenberg approach.

I also think there should be an option to remove the default Wordpress blocks to keep Flynt components clean and simple and avoid mixing them with default Wordpress blocks.

Happy to hear from you and have some insights or thoughts from you.

PS:
The new and simpler approach back to the Wordpress roots is really refreshing and fun to work with! Great job!

**Comment by bdbch** [comment]
I'm stuck right now at rendering the output. Registration of the block and field group was successful as seen in the following screenshot:

![image](https://user-images.githubusercontent.com/6538827/57478199-a4631e00-729a-11e9-8176-81e2250dddae.png)

I can also edit the data and show fields in the gutenberg editor.

![image](https://user-images.githubusercontent.com/6538827/57478241-bd6bcf00-729a-11e9-98fb-0f05b8473a8a.png)

I'm using a var_dump of the passed data as the renderCallback right now so I can see data-passing actually works. The problem now is rendering the output via Twig. It looks like the Twig-Environment and correct renderComponent function is inside the `TwigExtensionFlynt.php` file with now way to render it directly.

Using `Timber::render` requires the components template file path. Do we have a util function to get a components template twig path by component name?

**Comment by bdbch** [comment]
Rendering is working now. Needs some more work and refactoring because of some duplicate code.

![image](https://user-images.githubusercontent.com/6538827/57480432-f9556300-729f-11e9-91ba-a16ea8b46207.png)

Looking into style and script enqueuing for the component previews (and why the full-width option is not working properly).

**Comment by bdbch** [comment]
![image](https://user-images.githubusercontent.com/6538827/57497122-a3e87880-72d6-11e9-8372-c70b6266a9b6.png)

Rendering via the_content works and enqueuing scripts and styles also works fine. Global styles are currently breaking the Wordpress UI.

**Comment by bdbch** [comment]
Moving development progress into PR #19

**Comment by steffenbew** [comment]
We've been very excited to see the ACF support for Gutenberg with ACF blocks and it can be pretty straight forward to support them as you demonstrated in #19, but the interface for ACF fields is still unsatisfactory when switching into preview mode. That tiny sidebar is nice for few fields, but once you add a repeater or bigger field group, it looks broken and we don't want to provide our clients with that experience. Also, the preview mode with ACF might make the content manager assume it's a 1:1 page preview, but it isn't, due to extra Gutenberg editor styles. So we decided not to support it for the time being, in favor of an easy to use backend interface.

I would also like to avoid having 2 approaches side by side, but don't feel like it's a good time to ditch the standard ACF fields approach just yet. So it's a no for Gutenberg at this point in time.
