### ISSUE TITLE
Base Style Select Field styling is off on Firefox

### ISSUE THREAD

**Issue by bdbch** [flyntwp/flynt#185]
**Problem**
The select field seems to be a bit off on Firefox (MacOS). I presume the behaviour is the same on other operation systems.

**Expected Behaviour**
The select field should look the same as in Chrome

**Information**
Firefox Version: Firefox 71.0b10
MacOS Version: MacOS Mojave 10.14.6

<img width="367" alt="grafik" src="https://user-images.githubusercontent.com/6538827/69173476-25c82280-0b00-11ea-9b1d-b593ec58946a.png">

**Comment by steffenbew** [comment]
Thanks! I quickly checked on Firefox & Chrome if setting `line-height: 1.75` fixes it for both and it does. But will look more thoroughly into it and do proper cross browser checks.

**Comment by bdbch** [comment]
Thanks! Congrats to the 1.0.0 launch btw. 🎉
