### ISSUE TITLE
Oembed.php: vimeo embed warning

### ISSUE THREAD

**Issue by nikola-bleech** [flyntwp/flynt#21]
When embedding `vimeo` videos, a warning message appears:
```
Warning: DOMDocument::loadHTML(): htmlParseEntityRef: expecting ';' in Entity, line: 1 in /web/app/themes/.../lib/Utils/Oembed.php on line 24 
```

It can be suppressed by prepending the line with an `@` symbol:

`@$Dom->loadHTML($iframeTagHtml);`

**Comment by steffenbew** [comment]
Thanks. Tested on latest version and it doesn't seem to happen anymore.
