### ISSUE TITLE
a BIG contradiction

### ISSUE THREAD

**Issue by szepeviktor** [flyntwp/flynt#219]
Timber is a fine software - 2.x is coming soon

ACF is a *poorly written* one-man-show for non-tech-savvy people thus [is not sustainable](https://github.com/szepeviktor/acf-get/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).

How cloud they marry?

**Comment by domtra** [comment]
Hi @szepeviktor, you do have kind of a point. But our goal is not do provide the technically cleanest and most modern PHP framework out there. If it was, we probably would not be using WordPress at all.
We want to offer developers a head start and an efficient way to develop component based WordPress themes.
ACF is already used by many developers. It also has a lot of features that you do not find in other meta box plugins. The most used feature for us is the flexible content field. We have considered using other options. CMB2 and carbon fields for example. For now ACF Pro is still our best bet, as the others could not convince us to move away from it.
Timber provides a lot of great features. It also has its gotchas, though. Also, the entry barrier is quite high for a 'regular' WordPress developer. That is why we also looked at not using Timber at all. However, at the moment that pros still outweigh the cons.
We are actually really happy with this marriage. I hope you get our point and when you try flynt, see how productive you can be with it.

**Comment by szepeviktor** [comment]
I get is. _'Regular' WordPress developers_ make up the masses, the user base.
