### ISSUE TITLE
Gradually adding unit tests

### ISSUE THREAD

**Issue by szepeviktor** [flyntwp/flynt#225]
Do you plan to introduce simple unit tests?
Codeception is a very good platform: https://github.com/lucatume/wp-browser

**Comment by domtra** [comment]
Hi @szepeviktor, 
at the moment we do not have plans to add automated tests. We used to have test for our legacy libraries used in flynt. Those were based on PHPUnit. This would also be the preferred way to test flynt features.
Adding end to end or integration tests are currently not something we are considering.
