### ISSUE TITLE
composer install - command not found

### ISSUE THREAD

**Issue by kajahaler712** [flyntwp/flynt#226]
Hi, I'm tying to install Flynt on my wordpress on localhost. I'm having troubles with composer install:

***-MBP:flynt-1.1.1 ***$ composer install
-bash: composer: command not found

Can please someone help me with this?

**Comment by szepeviktor** [comment]
Try installing Composer the tool itself: https://getcomposer.org/download/

I do it this way: https://github.com/szepeviktor/debian-server-tools/blob/master/debian-setup/packages/_package-php-composer
