### ISSUE TITLE
feat: Ideas to make it reusable accross projects

### ISSUE THREAD

**Issue by trompx** [flyntwp/flynt#233]
Hello,

I am familiarizing with the framework and really like what you have achieved, thanks for sharing with the community!

I was planning to use it as a core-framework for multiple websites, thus creating a local composer package that I'd pull into each site, that would bring common Components (especially admin ones), the logic (most of the /lib files and /inc files) and admin assets.
Website specific content/settings would need to be outside of the core framework:
- Components (thus should be loadable from multiple folders)
- global frontend assets
- inc/customPostTypes
- inc/customTaxonomies
- inc/fieldsGroups

Have you considered at one point doing this kind of setup?

I stumbled upon stoutlogic ACF builder which seems to do the same as your acf-field-group-composer but in a less verbose way, is there any major features missing in ACF builder that would prevent the switch?

**Comment by domtra** [comment]
@trompx, thanks for your input. we used to have a more separated structure for flynt but decided to go with the starter theme for now. 
the theme is supposed to be a boilerplate. so usually you will customize your components for each new theme. 
if you want to share code between different project, the best way to do this at the moment is to use a multisite and write some additional logic to only load the stuff that you need. if you do not want to do this the only thing that you can share in a straight forward way are components.
for this, create a folder that contains all of the component folders as subfolders. you can place this folder in the `./Components` folder and all of the subcomponents will be included automatically. You then have to manually adjust your field groups to actually include these new components.
anything more than this is currently out of scope. but if there is demand for something like this, we might think about adding a more composable structure again.
