### ISSUE TITLE
missing autoload.php

### ISSUE THREAD

**Issue by Nsokyi** [flyntwp/flynt#237]
When I go through the install process and then activate the theme I get the following error in the browser: _Warning: require_once(/var/www/html/wp-content/themes/flynt-1.1.1/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/wp-content/themes/flynt-1.1.1/functions.php on line 7_ 
I feel like I have missed a step but I'm not sure what?

**Comment by proweb** [comment]
Did you install composer dependencies throught:
```
composer install
```
See - https://getcomposer.org/doc/03-cli.md#install-i

**Comment by Nsokyi** [comment]
Yea, I did then I got a message about not being able to find the Composer Jason file, after that I edited the composer.json file and it now works. Thanks

**Comment by domtra** [comment]
@Nsokyi great that you could figure it out. @proweb thanks for stepping in.
