### ISSUE TITLE
Child theme support

### ISSUE THREAD

**Issue by DanProudfoot** [flyntwp/flynt#24]
Hi, I don't do much Wordpress, and just wanted to ask if child theme is supported with Flynt...and if so, what do I have to do to get it up and running?

Thanks

**Comment by domtra** [comment]
Hi, we have not used flynt as a child theme yet and also not made any adjustments for that. flynt at the moment is more a boilerplate with a build process. We do not see the need for being able to create a child theme and would not necessarily be able to provide backward compatible updates for the parent theme. 
This might change, however, in the next months as flynt continues to evolve. We'll keep everyone updated.
If you have any other questions, feel free to ask.
