### ISSUE TITLE
Call custom function not working

### ISSUE THREAD

**Issue by mauricenaef** [flyntwp/flynt#242]
I have a custom non WordPress function I would like to call, and tried the Timber docs with the examples mentioned there but it only throws errors.

Basically I would like to call the following function in the templates where needed with arguments to return the appropriate SVG Icon.

`function get_svg_icon( $icon , $class = NULL  ) {
	$svg = '<svg class="icon icon-' . $icon . ' ' . $class . '"><use xlink:href="'. get_bloginfo('template_url') . '/dist/assets/icons/symbol-defs.svg#' . $icon . '"></use></svg>';
	return $svg;
}`

**Comment by domtra** [comment]
@mauricenaef did you try in your template
```twig
{{ fn('get_svg_icon', '$icon argument', 'class argument') }}
{# OR #}
{{ function('get_svg_icon', '$icon argument', 'class argument') }}
```
? if this does not work, maybe the file in which you define this function is not loaded before you do the rendering. where did you put this function?
normally it should work. there are some other ways to achieve this as well. see https://timber.github.io/docs/guides/functions/ or https://timber.github.io/docs/guides/extending-timber/#adding-functionality-to-twig

Hope this helps.

**Comment by mauricenaef** [comment]
I assumed that all files in the inc directory are loaded with the function.php file, so my custom PHP function file is in it. I would like the function to be available in every component and template, do I need to import the file?

Thanks

**Comment by domtra** [comment]
thank is strange. all files in `./inc` are required up front. all files in `./lib` are psr4 autoloaded.
is the function maybe in a namespace? then you need to specify that namespace in the twig `fn` call as well.
would it be possible for you to share the code and filenames/locations of the two files. is the code publicly available? then i can have another look.

**Comment by mauricenaef** [comment]
🙈 OMG yes I falsely declared a namespace and didn't get the proper error message .. sorry for the trouble and thanks for helping out as well as the really awesome starter!
