### ISSUE TITLE
WPML Language Drop Down List doesn't add to the header menu

### ISSUE THREAD

**Issue by forevereffort** [flyntwp/flynt#243]
Hello 

```
add_filter('Flynt/addComponentData?name=SiteHeader', function ($data) {
    $data['header_menu'] = new Timber\Menu('header_menu');
    $data['logo'] = [
        'src' => Asset::requireUrl('Components/SiteHeader/Assets/logo.png'),
        'alt' => get_bloginfo('name')
    ];

    return $data;
});
```

```
      {% for item in header_menu.items %}
        <li class="{{ item.classes | join(' ') }}">
          <a href="{{ item.link }}">{{ item.title }}</a>
          {% if item.children %}
            <ul class="submenu">
              {% for child in item.children %}
                <li class="{{ child.classes | join(' ') }}">
                    <a href="{{ child.link }}">{{ child.title }}</a>
                </li>
              {% endfor %}
            </ul>
          {% endif %}
        </li>
      {% endfor %}
```

for navigation, I used the above code.
and I want two languages for English and Portugues.
but when I set Menu language switcher on WPML, only the current language(English) item is added to the header menu.

How can I fix that issue?

Regards

**Comment by koukouchris** [comment]
Hi @forevereffort if I understand correctly you switch the site to the other language and you still see the main language menu on the second language? 

You don't need to write any special code for the language switch to work for the menu. 

So I would first start with making sure the menu of the second language is correctly set on admin. Creating a menu on second language and assign it as a translation of the main language menu, in the same position and that it has items (it's not empty). 
You can see the [WPML Documentation](https://wpml.org/documentation/getting-started-guide/translating-menus/#option-1-translating-menus-manually) on how to translate menus.

Most common outcome if the second language menu is not set correctly on admin is to see the main language items on the second language also.

**Comment by forevereffort** [comment]
Thank you very much. It works for me!!!

**Comment by forevereffort** [comment]
> Hi @forevereffort if I understand correctly you switch the site to the other language and you still see the main language menu on the second language?
> 
> You don't need to write any special code for the language switch to work for the menu.
> 
> So I would first start with making sure the menu of the second language is correctly set on admin. Creating a menu on second language and assign it as a translation of the main language menu, in the same position and that it has items (it's not empty).
> You can see the [WPML Documentation](https://wpml.org/documentation/getting-started-guide/translating-menus/#option-1-translating-menus-manually) on how to translate menus.
> 
> Most common outcome if the second language menu is not set correctly on admin is to see the main language items on the second language also.

**Comment by forevereffort** [comment]
> > Hi @forevereffort if I understand correctly you switch the site to the other language and you still see the main language menu on the second language?
> > You don't need to write any special code for the language switch to work for the menu.
> > So I would first start with making sure the menu of the second language is correctly set on admin. Creating a menu on second language and assign it as a translation of the main language menu, in the same position and that it has items (it's not empty).
> > You can see the [WPML Documentation](https://wpml.org/documentation/getting-started-guide/translating-menus/#option-1-translating-menus-manually) on how to translate menus.
> > Most common outcome if the second language menu is not set correctly on admin is to see the main language items on the second language also.

Thank you very much.

**Comment by forevereffort** [comment]
@koukouchris Thank you very much
