### ISSUE TITLE
Restrict access to .twig files

### ISSUE THREAD

**Issue by HanifBirgani** [flyntwp/flynt#250]
I think it's better to restrict access to .twig files in the webserver config level.

Apache:
```
<FilesMatch ".+\.twig$">
    <IfModule mod_authz_core.c>
        # Apache 2.4
        Require all denied
    </IfModule>
    <IfModule !mod_authz_core.c>
        # Apache 2.2
        Order deny,allow
        Deny from all
    </IfModule>
</FilesMatch>
```

Nginx:
```
location ~- \.twig$ {
  deny all;
}
```

**Comment by domtra** [comment]
Hi @HanifBirgani , thanks for your comment. I agree that it is a good idea to restrict access to the twig files. Usually I would think to leave the configuration of the webserver to the theme user. With php files in the theme folder it is basically the same.
What would you suggest for Flynt, or any wordpress theme? Do you have an example what other themes do? Write to the htaccess or just give advice in wp-admin?

**Comment by HanifBirgani** [comment]
I suggest a .htaccess rewrite rule on theme init.

The sage theme suggested the rules on the [installation page](https://roots.io/docs/sage/9.x/installation/#server-configuration) (for .blade.php files) but did not force users to do it.

**Comment by HanifBirgani** [comment]
Is there any update on this issue?

**Comment by steffenbew** [comment]
@domtra is currently out of office until the end of the week. I'm sure he will look into this again when he's back.
