### ISSUE TITLE
Question: Preloaded Components

### ISSUE THREAD

**Issue by isaacbraun** [flyntwp/flynt#253]
Hello,

I'm developing a website using Flynt and have really enjoyed is so far. I'm curious if there's an good way to pre-populate specific components on and page with the same template, just like is available with standard ACF. I have tried to find a solution by digging around in the code, but haven't come up with anything. If this is possible and someone could explain it to me I would really appreciate it. 

Thanks

**Comment by pixelsaft** [comment]
You can render components directly inside twig files. 

You find an example here: [templates/index.twig](https://github.com/flyntwp/flynt/blob/master/templates/index.twig)

The component "GridPostsArchive" will be rendered with additional parameters.

For static and/or repeating content you can also a new group inside the "Translatable Options" and use these content at each required pages.

**Comment by isaacbraun** [comment]
Thanks for the quick response and the advice. I think I should have made myself more clear. I would like to have components already added in a new page that the end-user can edit. For example, a Hero Component and Contact Information Component that would already be there when they create a new page, but would require them to still fill out the fields. If I am understanding correctly, the options you gave me wouldn't work in this way, correct? I appreciate the help.

**Comment by pixelsaft** [comment]
We do this always inside a new component **_(i don't know if this is the best way, it actually works)_**:

1. Duplicate the complete component folder of the component who should appear at new pages inside the backend
2. Rename the duplicated component folder and change/modify the content of the files from the duplicated compoment (**functions.php, scripts.js, etc.**) according to the new component name
3. Replace the function **getACFLayout()** with an action and register the field group
```
add_action('Flynt/afterRegisterComponents', function () {
    ACFComposer::registerFieldGroup([ 
        'name' => 'XXX', // your component name
        'title' => 'XXX', // component main title inside backen
        'style' => 'default',
        'menu_order' => 99,
        'fields' => [
        ]
        …
        ],
        'location' => [
            [
                [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page'
                ],
                [
                    'param' => 'page_type',
                    'operator' => '!=',
                    'value' => 'posts_page'
                ]
            ]
        ]
    ]);
});
```
4. I modify the component according to the requirements
5. I add this component with `{{ renderComponent('XXX') }}` into [_document.twig](https://github.com/flyntwp/flynt/blob/master/templates/_document.twig)

**Comment by isaacbraun** [comment]
Thank you so much! This shows the component fields in the back end and allows me to edit the fields, but the renderComponent is rendering without any inputs. Anywhere I locate the renderComponent('xxx') function within _document.twig it does same thing. The function doesn't seem to read the functions.php file, but rather renders it statically.

**Comment by pixelsaft** [comment]
Sound like there is a conflict within the namespace. Did you also changed the namespace at the functions.php of the duplicated component? The namespace should also have the same name as the component folder.

**Comment by isaacbraun** [comment]
There shouldn't be. I've double and triple checked it. 

This is where I've included it in _document.twig
`<main class="mainContent"> 
          {{ renderComponent('HeroPreLoad') }}
          {% if function('post_password_required') %}
            {{ function('get_the_password_form') }}
          {% else %}
            {% block content %}
              No <code>{{ '{% block content %}' }}</code> defined for this template.
            {% endblock %}
          {% endif %}
        </main>`

and I attached my functions.php in a .txt file.

I really appreciate the help and apologize for my inexperience.


[functions.txt](https://github.com/flyntwp/flynt/files/4718986/functions.txt)

**Comment by isaacbraun** [comment]
It's a custom component, a very simple hero with an image and title

**Comment by pixelsaft** [comment]
I think you can solve the problem inside the twig file from the component. The variables must also modified by hand inside the twig-file.
For example (according to your functions.php) the title field you can get with **post.custom.title** – i think.

**Comment by isaacbraun** [comment]
You're amazing! Thanks a lot! The title works but post.custom.image.src doesn't work and .image just returns a number.

**Comment by pixelsaft** [comment]
I wrote a component for this purpose – however this is not part of question ;) But i think i can take a look over your component if you send me the complete component.

**Comment by isaacbraun** [comment]
https://github.com/isaacbraun/FlyntHeroPreLoad

**Comment by pixelsaft** [comment]
Put this: `**{{Image(post.custom.image).src}}**`
instead of: `{{ post.custom.image }}`
… inside your twig-file and take a look into the timber documentation: [Timber\Image](https://timber.github.io/docs/reference/timber-image/)

**Comment by isaacbraun** [comment]
That works! Thank you so much! I'll make sure to read through more Timber documentation.

**Comment by steffenbew** [comment]
@pixelsaft Thanks for your amazing support!
