### ISSUE TITLE
Main Nav Support Drop down

### ISSUE THREAD

**Issue by purchasingtoolpak** [flyntwp/flynt#254]
Is the main navigation supposed to support drop down menus? It looks like the footer nav has a sub-menu with {% if item.get_children and level + 1 <= maxLevel %} but it doesn't work.

I tried to use the timber nav walker but couldn't get the css to work using level-1 and level 2. It appears that the css is missing for level-0.

Any help would be appreciated.

Dave

**Comment by pixelsaft** [comment]
I think, the main navigation doesn’t support dropdown items, out-of-the-box and at the moment. But with some customization into the navigation components it shouldn’t something big.

**Comment by purchasingtoolpak** [comment]
The issue I'm having is that the sub menu (level--1) does not render.

Here is my index.twig file in the Navigation Main folder:
<nav is="flynt-navigation-main" class="flyntComponent">
  <div class="wrapper">
    <div class="container centerMaxWidthContainer">
      <a class="logo" href="{{ site.link }}">
        <img class="logo-image" src="{{ logo.src }}" alt="project-sunshine-canada-logo">
      </a>
      {% if menu %}
      <nav class="navigation">
        {% include 'menu.twig' with { 'items': menu.get_items, 'level': '0', 'maxLevel': maxLevel } only %}
      </nav>
      {% endif %}
      {% if contentHtml %}
      <div class="content">{{ contentHtml|e('wp_kses_post') }}</div>
      {% endif %}
    </div>
  </div>
</nav>

Here is my include menu.twig file in the Navigation Main:
<ul class="menu menu--level-{{ level }}">
  {% for item in items %}
	{% set hasChildren = item.get_children is defined and item.get_children|length > 0 %}
    <li class="{{ item.classes | join(' ') }}">
      <a class="menu-link" href="{{ item.link }}"{% if item.target %} target="{{ item.target }}"{% endif %}>{{ item.title }}</a>
      
	  {% if hasChildren %}
	  	<p>Yes has children</p>
        
		<ul class="menu menu--level-1">
			<li class="{{ item.classes | join(' ') }}">
      			<a class="menu-link" href="{{ item.link }}"{% if item.target %} target="{{ item.target }}"{% endif %}>
				  {{ item.title }} Contact Us</a></li>
		</ul>
      {% endif %}
    </li>
  {% endfor %}
</ul>

The top level menu works fine.  When the main menu has children, {% if hasChildren %) is true. However the sub menu does not appear and the top level menu is repeated. See below for the rendered html:

<nav class="navigation">
  <ul class="menu menu--level-0">
    <li class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-29 menu-item-has-children">
      <a class="menu-link" href="//localhost:3000/wordpress/about/">About Us</a>
      <p>Yes has children</p>
      <ul class="menu menu--level-1">
        <li class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-29 menu-item-has-children">
          <a class="menu-link" href="//localhost:3000/wordpress/about/">
            About Us Contact Us</a></li>[note: top level nav repeats - no sub menu]
      </ul>
    </li>

Any help debugging would be appreciated.

**Comment by koukouchris** [comment]
@purchasingtoolpak On second level you are still in the `{% for item in items %}` loop. `item` is still the first level, second level array lives under `item.get_children` or `item.children` not `item`. Can you try another loop into `item.get_children`? 

Also dumping/printing your data  (either `[twig](https://twig.symfony.com/doc/2.x/functions/dump.html)` or in your `functions.php`) can be helpful when dealing with issues like this to have an overview of where is what. :)

**Comment by pixelsaft** [comment]
I did a short test. To get all 2 level elements inside the navigation you can use the following snipped inside the [index.twig](https://github.com/flyntwp/flynt/blob/master/Components/NavigationMain/index.twig) from the [NavigationMain](https://github.com/flyntwp/flynt/tree/master/Components/NavigationMain) Component:
```
<nav class="flyntComponent" is="flynt-navigation-main">
	<div class="wrapper">
		<div class="container centerMaxWidthContainer">
			<a class="logo" href="{{ site.link }}">
				<div class="logo-site-name">{{ site.name|trim }}</div>
				<div class="logo-site-description">{{ site.description|trim }}</div>
			</a>
			{% if menu %}
				<ul class="menu">
					{% for item in menu.items %}
						<li class="menu-item {{ item.current ? 'menu-item--current' }}">
							<a class="menu-link" href="{{ item.link }}" {{ item.target == '_blank' ? 'target="_blank" rel="noopener noreferrer"' }}>{{ item.title }}</a>
							{# Simple 2 level navigation start #}
              {% if item.get_children %}
								<ul class="menu menu-submenu">
									{% for item in item.get_children %}
										<li class="menu-item {{ item.current ? 'menu-item--current' }}">
											<a class="menu-link" href="{{ item.link }}" {{ item.target == '_blank' ? 'target="_blank" rel="noopener noreferrer"' }}>{{ item.title }}</a>
										</li>
									</ul>
								{% endfor %}
							{% endif %}
              {# Simple 2 level navigation end #}
						</li>
					{% endfor %}
				</ul>
			{% endif %}
		</div>
	</div>
</nav>
```
**Note: This code snipped doesn’t support deeper navigation levels.**

I hope this helps.

**Comment by purchasingtoolpak** [comment]
OK, only need 2 levels and this is working great. If you could share the _style.scss that would be appreciated.

THANKS

**Comment by pixelsaft** [comment]
@purchasingtoolpak, Great to hear that it work now. 

There a many ways to style a menu with SCSS and you did not wrote anything about what kind of styles you like to implement.

If you send me an example, I'll see what I can do for you.

And keep in mind that the next step after customizing the main navigation is usually to adjust the mobile navigation ;)

**Comment by purchasingtoolpak** [comment]
No further concerns here. It would be great if flynt came out of the box with a multi-level menu. Most WordPress themes seem to support. Thanks for all the help on this pixelsaft!

**Comment by steffenbew** [comment]
@purchasingtoolpak Thanks for your feedback. We're considering to extend the navigation to support multiple levels. In the past, we noticed that there are many different concepts to a multi-level navigation and thus wanted to keep it simple, instead of committing to one specific case.

**Comment by CodeConvergence** [comment]
Please excuse me for opening this after almost a year.
May I ask @timohubois - is your snippet still relevant for v1.4.?

Using your code I am able to bring in the sub menu items, but the styling of the children loop is so off I'm wondering if there was an update.

**Comment by CodeConvergence** [comment]
Hi Timo,
Thanks for the quick response. Knowing that it is only a styling issue helps.
Maybe, if components are shared as proposed in [Sharing Components #377](https://github.com/flyntwp/flynt/discussions/377), then a dropdown may become available, as a starter at least, for those who would like to use it.

**Comment by purchasingtoolpak** [comment]
If you’d like the code with the css for a drop down menu let me know. I used the bulma css to style the menu.

 

Dave

**Comment by CodeConvergence** [comment]
Hi Dave,

Thank you! I really like the menu you are using on thearcofhr.org, sharing something like that would (imho) be great for anyone getting started with Flynt. I’m using TailwindCSS, perhaps seeing the way you’ve used Bulma will allow me to do the same with TW or just plain CSS. 

May I email you at purchase… ?

**Comment by purchasingtoolpak** [comment]
Here is the link on github for the drop down navigation menu.

 

https://github.com/purchasingtoolpak/NavigationMain

 

Hope this helps.

 

Dave

**Comment by CodeConvergence** [comment]
Thanks so much!

**Comment by CodeConvergence** [comment]
Quick feedback: Your component works perfectly and implementation was a breeze :)
Bulma’s Sass foundation is a good fit with Flynt, so customization was smooth sailing.

Would you be willing to share your mobile navigation component too?

Thanks again!

**Comment by purchasingtoolpak** [comment]
OK, I just added the Navigation Burger here.

 

https://github.com/purchasingtoolpak/NavigationBurger

 

Hope this helps.

 

Dave

**Comment by CodeConvergence** [comment]
Thank you so much Dave!
