### ISSUE TITLE
How can I use Gutenberg only for wordpress default Post type?

### ISSUE THREAD

**Issue by forevereffort** [flyntwp/flynt#256]
Flynt is very good. **but now the Gutenberg is disabled for WordPress default post type?** I would like to use the Gutenberg only for Wordpress default post type, so not use ACF flexible content like now. how can I do this?

**Comment by HanifBirgani** [comment]
Edit `inc/removeEditor.php` and comment this line:

```php
remove_post_type_support('post', 'editor');
```

**Comment by forevereffort** [comment]
> Edit `inc/removeEditor.php` and comment this line:
> 
> ```
> remove_post_type_support('post', 'editor');
> ```

Thank you very much. It works well
