### ISSUE TITLE
Minify JS/CSS

### ISSUE THREAD

**Issue by darksns** [flyntwp/flynt#259]
Hi, how can I activate the minification of the css and js files?

Thanks

**Comment by steffenbew** [comment]
Hi @darksns, to minify the output of your css and js files, run the following command in your cli:
`npm run build`

This will run multiple command to prepare your code for production use. See the [package.json](https://github.com/flyntwp/flynt/blob/master/package.json#L13) file for more details on which commands are run.

**Comment by Fabiato** [comment]
Hi,

I tried to run `npm run build` but css and js files are always unminified.
My environment is set to production.
