### ISSUE TITLE
Browsersync not injecting scss/js

### ISSUE THREAD

**Issue by hgblu-sammosna** [flyntwp/flynt#260]
Browser-sync does not inject component-specific SCSS and JS even if it compiles successfully. What could it be?

**Comment by clementducerf** [comment]
Try enabling websockets in your apache configuration ('mod_proxy_wstunnel') and setting : 


`browserSync: {
    ghostMode: false,
    open: false,
    proxy: {
      target: host,
      **ws: true**
    },`

in build-config.js

**Comment by domtra** [comment]
@hgblu-sammosna it could be that you are running on an os or filesystem that does not support file events.
chokidar, the file watcher that browser-sync uses, can fall back to polling. You have to enable this in the config, however.
As described [here](https://www.browsersync.io/docs/options#option-watchOptions), try adding
```js
watchOptions: {
  usePolling: true,
  interval: 100
}
```
to the browserSync config in the `build-config.js` file.

Let me know if I could help you with this.
