### ISSUE TITLE
Remove jQuery

### ISSUE THREAD

**Issue by HanifBirgani** [flyntwp/flynt#274]
I have searched the whole front-end codes of Flynt to find jQuery usages and got the following results:

- getScript (2 files)
- DOM Selector (6 files)
- Event handler (6 files)
- Class manipulation (3 files)
- Get element width/height (2 files)
- Find (1 file)
- Data attribute handling (2 files)
- Style manipulation (1 file)

All of the functions above could be written in lightweight vanilla js for better optimization, speedup page loads, and reduce depending on massive old libraries like jquery. What do you think about getting rid of jquery?

**Comment by domtra** [comment]
Thanks for your suggestion @HanifBirgani,
you are right, that there is not a lot of jQuery specific code in the base components. However, there is more in the premium components and also in some components that we do not publish at all.
I agree, that jQuery brings some bloat along and that this can be improved. 
Moving away from jQuery would result in a major version bump. At the moment we are focused on stabilising flynt as a whole.
In a future version, we will probably either entirely drop jQuery, or use a new build based on ecmascript modules.
In the meantime it should also be straight forward to remove jQuery from a new flynt installation. Maybe somebody can create a codemod to do so. 
Hope this answers you question.
