### ISSUE TITLE
Create Action Ajax Wordpress on Component

### ISSUE THREAD

**Issue by darksns** [flyntwp/flynt#280]
Hello,
I'm having trouble creating an ajax action with:

function test_callback() {
    echo 'test';
}
add_action ('wp_ajax_test', 'test_callback');
add_action ('wp_ajax_nopriv_test' ',' test_callback ');

If I insert the declaration on the function.php file of the component, wordpress does not see it.
If instead I insert the declaration on the file inc/theme.php then it works correctly.

**Comment by domtra** [comment]
Hi @darksns.

The issue comes from namespaces that are used in almost every file in flynt. `inc/theme.php` is one of the few files without a namespace being defined.

If you want to make your code work in the `functions.php` try
```php
function test_callback() {
    echo 'test';
}
add_action('wp_ajax_test', 'Flynt\\test_callback');
add_action('wp_ajax_nopriv_test', 'Flynt\\test_callback');
```

Hope this helps!
