### ISSUE TITLE
Default component added to a new page?

### ISSUE THREAD

**Issue by proteinone** [flyntwp/flynt#282]
Hi team Flynt!

I have a question about the Field Groups - is it possible to have a 'default' component added to a newly created page in the admin?

For example, with the code below, I'm currently only registering 1 component in this particular field group, so when the client creates a new page (or taxonomy as this would be), it would be handy if this component was added to the page by default.

Any thoughts or tips would be much appreciated!

Cheers,
Tim

```
<?php

use ACFComposer\ACFComposer;
use Flynt\Components;

add_action('Flynt/afterRegisterComponents', function () {
    ACFComposer::registerFieldGroup([
        'name' => 'moduleComponents',
        'title' => 'Module Components',
        'style' => 'seamless',
        'fields' => [
            [
                'name' => 'moduleComponents',
                'label' => __('Module Components', 'flynt'),
                'type' => 'flexible_content',
                'button_label' => __('Add Component', 'flynt'),
                'layouts' => [Components\TopicTemplate1\getACFLayout()],
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'taxonomy',
                    'operator' => '==',
                    'value' => 'module',
                ],
            ],
        ],
    ]);
});
```

**Comment by steffenbew** [comment]
Hi Tim,

as far as I know, ACF does not provide a functionality to pre-fill flexible content fields with layouts.
It might be possible to achieve that with some backend JavaScript, but I haven't tried it myself.

What we like to do is adding a component as a fixed layout to a specific custom post type when needed. This might be handy for things like a hero header, which should always appear on a page, or if left empty, would not show up.
I assume this is not what you're looking for though.

Let me know if you find a solution to adding 'default' components! I would be happy to learn about it.

Best,
Steffen

**Comment by proteinone** [comment]
Thanks @steffenbew !

That approach you mentioned is exactly what I ended up doing.  The more I thought about it, the more it made sense to use the fixed layout approach, rather than try to dynamically import a pre-filled flexible field.

**Comment by bradmurphy** [comment]
> Hi Tim,
> 
> as far as I know, ACF does not provide a functionality to pre-fill flexible content fields with layouts.
> It might be possible to achieve that with some backend JavaScript, but I haven't tried it myself.
> 
> What we like to do is adding a component as a fixed layout to a specific custom post type when needed. This might be handy for things like a hero header, which should always appear on a page, or if left empty, would not show up.
> I assume this is not what you're looking for though.
> 
> Let me know if you find a solution to adding 'default' components! I would be happy to learn about it.
> 
> Best,
> Steffen

How would you add a default component int his case for a custom post type?
