### ISSUE TITLE
ExternalScriptLoader is never used

### ISSUE THREAD

**Issue by frontant** [flyntwp/flynt#283]
Hello,
I just inspected the code in `assets/scripts/ExternalScriptLoader` and it seems to be used nowhere. Is it a bug?

**Comment by domtra** [comment]
Hi @frontant ,

this is not a bug. We used this in the past and still sometimes use it in projects.

However, this function is not used in flynt currently, so we will probably get rid in the future.

Thanks for pointing this out!
