### ISSUE TITLE
Min. PHP

### ISSUE THREAD

**Issue by szepeviktor** [flyntwp/flynt#294]
What is the minimum PHP version?

Please add it to composer.json.
Thanks.

**Comment by domtra** [comment]
Hey @szepeviktor,

it is 7.0. I just added it to the composer.json. Will be part of the next release.

Thanks for the question!

**Comment by szepeviktor** [comment]
You're welcome.

https://github.com/flyntwp/flynt/commit/128406237b96fa44f0e337a28a7252cadb0c98da
