### ISSUE TITLE
All Components are not showing in backend editor

### ISSUE THREAD

**Issue by jmodanwal** [flyntwp/flynt#302]
Hi
I have installed the theme but I can see there are total 9 components showing into editor.
![image](https://user-images.githubusercontent.com/54843020/91261128-53c44c80-e78d-11ea-84a2-e7e7829ea6bb.png)

I can see there are 21 components files into theme but only 9 are rendering.

Please help me ASAP.

Thanks

**Comment by eddiepantoja** [comment]
Portions of the theme such as search, nav, and footer are components. Those components would not be in the page editor. I think the nine that you are seeing is the page editor is correct.

**Comment by jmodanwal** [comment]
Yes, That 9 components are in page editor. Please tell me how to access rest of components in theme. Can I have any documentation for this ? Please share.

Thanks

**Comment by steffenbew** [comment]
Hi @jmodanwal, in Flynt, almost anything is a component, but not all are made to be added to a page.

Some components are statically added to a template, like the main navigation, or the blog post header. Please see the [templates/single.twig](https://github.com/flyntwp/flynt/blob/master/templates/single.twig) file for examples of statically and dynamically rendered components.

The components you're seeing in the page editor are flexible content layouts, which can be added dynamically to a page. For components to show up in the **Add component** dropdown, their field layouts need to be added to a field group file: [/inc/fieldGroups/pageComponents.php](https://github.com/flyntwp/flynt/blob/master/inc/fieldGroups/pageComponents.php).

I hope that helps with understanding the Flynt component architecture.

**Comment by jmodanwal** [comment]
Yes, I got it. Thanks a lot.

**Comment by steffenbew** [comment]
Hi @jmodanwal, happy I could help. I just published a tutorial to get started with Flynt: [The Beginner’s Guide to Developing a Custom WordPress Theme With Flynt](https://flyntwp.com/the-beginners-guide-to-developing-a-custom-wordpress-theme-with-flynt/). Hope it'll be valuable to you, or anyone else working with Flynt the first time.
