### ISSUE TITLE
CopyWebpackPlugin throws errors

### ISSUE THREAD

**Issue by frontant** [flyntwp/flynt#306]
Hello there,
I am currently working on a custom wordpress setup based on flyntwp (v1.3.0). My setup has custom assets and a few components. If I run the build process, I get this error:

```
LOG from copy-webpack-plugin
    <e> unable to locate 'Components/**/*' at '/home/anton/Projects/wordpress-starter-kit/themes/flynt/Components/**/*'
    <e> unable to locate 'assets/**/*' at '/home/anton/Projects/wordpress-starter-kit/themes/flynt/assets/**/*'
    + 12 hidden lines
```

My _'assets'_ and _'Components'_ directories contain files that are all ignored by the configuration in _build-config.js_ (*.js, *.scss, *.php, *.twig, screenshot.png, README.md). In the build process _CopyWebpackPlugin_ fails because it tries to copy empty directories. If I configure _CopyWebpackPlugin_ with _'noErrorOnMissing: true'_ all errors disappear:

```js
function getCopyConfig (source) {
  return {
    from: source,
    to: './',
    noErrorOnMissing: true,
    globOptions: {
      ignore: [
        '**/*.js',
        '**/*.scss',
        '**/*.php',
        '**/*.twig',
        '**/screenshot.png',
        '**/README.md'
      ]
    }
  }
}
```

**Comment by domtra** [comment]
@frontant thanks for the find. We did not have a component without any extra files so this hasn't occurred for us. I adjusted the config in #315 .
