### ISSUE TITLE
how to disable php lint for specific line?

### ISSUE THREAD

**Issue by forevereffort** [flyntwp/flynt#316]
Hello @domtra 

I am going to use **Walker_Comment** like the following

```
class CustomCommentWalker extends Walker_Comment
{
    protected function html5_comment($comment, $depth, $args)
    {
    }
}
```

after `npm run build`, I got the php lint issue : `Method name "CustomCommentWalker::html5_comment" is not in camel caps format`

`html5_comment` is wordpress standard function. so I can't change that function name.
how can I resolve this issue?

Regards

**Comment by domtra** [comment]
Hi @forevereffort ,

there are multiple ways to do that for any php codesniffer rule. In your case a would suggest
```
class CustomCommentWalker extends Walker_Comment
{
    protected function html5_comment($comment, $depth, $args) // phpcs:ignore PSR1.Methods.CamelCapsMethodName.NotCamelCaps
    {
    }
}
```

You can have a look [here](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-parts-of-a-file).
