### ISSUE TITLE
Call to undefined method Flynt\Utils\Options::createOptionPage()

### ISSUE THREAD

**Issue by karlbaumhauer** [flyntwp/flynt#336]
Hey guys,

I just set up wordpress using v5.5.3 and the flynt boilerplate. I also bought ACF pro v.5.9.3 and I get this error when activating the plugin:

`Fatal error: Uncaught Error: Call to undefined method Flynt\Utils\Options::createOptionPage() in /Users/[my-username]/Documents/DEV/[my-project-folder]/[my-repository]/[my-MAMP-project-directory]/wp-content/themes/[my-theme]/lib/Utils/Options.php:96 Stack trace: #0 /Users/[my-username]/Documents/DEV/[my-project-folder]/[my-repository]/[my-MAMP-project-directory]/wp-content/themes/[my-theme]/lib/Utils/Options.php(203): Flynt\Utils\Options::createOptionSubPage('global', 'Default') #1 /Users/[my-username]/Documents/DEV/[my-project-folder]/[my-repository]/[my-MAMP-project-directory]/wp-content/themes/[my-theme]/lib/Utils/Options.php(198): Flynt\Utils\Options::addOptions('Acf', Array, 'global', 'Default') #2 /Users/[my-username]/Documents/DEV/[my-project-folder]/[my-repository]/[my-MAMP-project-directory]/wp-content/themes/[my-theme]/inc/acf.php(45): Flynt\Utils\Options::addGlobal('Acf', Array) #3 /Users/[my-username]/Documents/DEV/[my-project-folder]/[my-repository]/[my-MAMP-project-directory]/wp-content/themes/[my-theme]/lib/Utils/FileLoader.php(66) in /Users/[my-username]/Documents/DEV/[my-project-folder]/[my-repository]/[my-MAMP-project-directory]/wp-content/themes/[my-theme]/lib/Utils/Options.php on line 96
There has been a critical error on your website. Please check your site admin email inbox for instructions.

Learn more about debugging in WordPress.`

I initially had an error caused by SSL connection to on api.wordpress.org which I fixed by adding: 

`curl_setopt($this->handle, CURLOPT_RESOLVE, array("api.wordpress.org:80:198.143.164.251", "api.wordpress.org:443:198.143.164.251", "downloads.wordpress.org:80:198.143.164.250", "downloads.wordpress.org:443:198.143.164.250"));` 

to my wp-includes/Requests/Transport/cURL.php file and adding:

`define( 'AUTOMATIC_UPDATER_DISABLED', true );` 
to my wp-config.php file.

What else can I do? 

thx for help

**Comment by domtra** [comment]
hi @karlbaumhauer ,

this is kind of a strange error, as the method `createOptionPage` should be defined as a protected static function in the same file where the error is thrown.

What PHP version are you using? Did you modify the Options.php file in some way?

**Comment by karlbaumhauer** [comment]
hi @domtra,

I am kind of feeling bad but the problem was the kebab-case in my project folder... for some reasons you can set up the project but nothing works as it is supposed to do... update check, plugin activation etc. 

I set up everything again with underscores in my project name and it works out of the box...

sorry for bothering you guys with such and "issue"

thanks and regards,
Karl
