### ISSUE TITLE
Safari Support

### ISSUE THREAD

**Issue by kilianso** [flyntwp/flynt#370]
Hey folks. Based on [caniuse](https://caniuse.com/?search=web%20components) customized built-in elements are currently not available in Safari. So something like`<div is="flynt-slider-images"></div>`will fail while `<flynt-slider-images></flynt-slider-images>` would work.

Do you have any build-magic going on to make this work or how do you deal with Safari?

**Comment by domtra** [comment]
Hi @kilianso , yes, we do include a polyfill for browsers that do not support custom built-in elements.
The current version of flynt includes https://github.com/WebReflection/document-register-element but for the next version we are switching to only https://github.com/WebReflection/custom-elements-builtin, potentially.
Hope this anwsers your question.
