### ISSUE TITLE
Sass sourcemaps configuration

### ISSUE THREAD

**Issue by djmtype** [flyntwp/flynt#375]
I wouldn't count this as a bug, maybe more of a configuration? 
During development, on the front end, the styles reference back to the parent `scss` file. In most cases, that's `main.scss`. 
For example, within `_base.scss`, my `html` element has a style of `min-height: 100vh`, when I look at my browser's devtools, the sourcemap shows it resides within `main.scss` instead of `_base.scss`. And that can be a real issue when it comes to debugging css.

**Comment by domtra** [comment]
Hi @djmtype, 
thanks you for your input. That is definitely something that should be working. We will put it in our backlog in see, when we can fit it in.
I will close the ticket for now.
