### ISSUE TITLE
Flynt and WooCommerce: Login form missing tags?

### ISSUE THREAD

**Issue by foobarrio** [flyntwp/flynt#382]
Hello, all. I'm posting this in the hopes that someone might be able to point me in the right direction as I've been scratching my head for quite some time now (and it's likely something silly, but my knuckles are so very tired from the scratching)...

When Flynt is the active theme, the [WooCommerce login form](https://github.com/woocommerce/woocommerce/blob/trunk/templates/myaccount/form-login.php#L34) renders with its `<form />` and `<input />` tags missing.

![image](https://user-images.githubusercontent.com/33064/122109153-a9ccb400-cde2-11eb-8848-f4c90108ce85.png)

When I switch the active theme to Twenty Twenty-One, the tags are there.

![image](https://user-images.githubusercontent.com/33064/122109337-de407000-cde2-11eb-91ed-3528b11b60fb.png)

I've disabled all plugins save WooCommerce and ACF PRO, and cleared my `functions.php` of filters and hooks, and torn out various parts of the Flynt theme, but no luck.

Any pointers would be very appreciated.

**Comment by dvdmierden** [comment]
Ran into this topic looking for the same issue: All (Woocommerce) form fields are missing / not rendered. 
Anybody got any pointers on how to implement those easily?

**Comment by foobarrio** [comment]
Just to follow up. My issue was self-inflicted: I was using [Block WYSIWYG](https://github.com/flyntwp/flynt/tree/master/Components/BlockWysiwyg) to add shortcodes to the page and the escaping of `contentHtml` prevented the output from rendering properly.

I created a custom component (super easy! thank you for creating this theme.) to output the shortcode and it works.
