### ISSUE TITLE
ACF field types with _ do not render correctly

### ISSUE THREAD

**Issue by see8ch** [flyntwp/flynt#392]
Running into an issue using any ACF field type that contains an `_` in the type. 

When the `page_link` type is used, there is an empty select box rendered.
```
[
    'label' => 'Link',
    'name' => 'link',
    'type' => 'page_link',
    'post_type' =>  [
        0 => 'post',
        1 => 'page',
    ], 
    'allow_null' => 0,
    'multiple' => 0
],
```

When the `color_picker` type is used, a standard text field is rendered.
```
[
    'label' => 'Color',
    'name' => 'color',
    'type' => 'color_picker',
    'default' => '#ffffff',
],
```

**Comment by domtra** [comment]
Hi @see8ch, unfortunately I can not see an issue here. For me those fields are rendering correctly. 

Are the fields already included in our base components, like `flexible_content`, `true_false`, `post_object` also not working?

Do you get any errors in the browsers console? Maybe some scripts are not executed correctly that should add the desired functionality.
