### ISSUE TITLE
Issue with "Module build failed"

### ISSUE THREAD

**Issue by marcotiberio** [flyntwp/flynt#397]
Hello,
Since yesterday afternoon, on an already installed theme, when running `npm start` I get the following error:
```
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (93)
```

In the meantime, I can't install the started theme anymore, as I get several errors after running `npm i`

Thanks for your help!

**Comment by danielsladejr** [comment]
@marcotiberio did you solve this? I'm having the same problem where `npm i` is giving me tons of errors when trying to install the theme.

**Comment by timohubois** [comment]
@marcotiberio and @danielsladejr what version of node do you currently use when you run `npm i`? Did you already tested it with node 12? If you use node 12 you can remove the "package.json" file and the "node_modules" folder inside the theme and and after that run `npm i` again.

**Comment by danielsladejr** [comment]
Using node 12 worked wonders. Thanks @timohubois!
