### ISSUE TITLE
Flexible Content field inside a Component Not Working

### ISSUE THREAD

**Issue by joeatduckpin** [flyntwp/flynt#406]
So I am trying to create a single component that allows a user to create a series of rows of content that will be either 1, 2, or 3 columns. The idea is that a single component could have a layout like this:

=====

1 Column of WYSIWYG-driven text
2 Columns of WYSIWYG-driven text
1 Column of WYSIWYG-driven text

=====

Naturally, I immediately went to the Flexible Content field, because that's pretty much what that field is made for in ACF

When I add a field group for my component, like this:

```
function getACFLayout()
{
    return [
        'name' => 'blockColumns',
        'label' => 'Block: Multi-Column Layout',
        'sub_fields' => [
            [
                'label' => 'Columned Section',
        	'name' => 'columned_section',
        	'type' => 'flexible_content',
        	'instructions' => 'Add a columned section.',
                 'button_label' => 'Add Section',
                 'layouts' => [
                    [
                        'name' => 'one_column',
        		'label' => 'One Column Content',
                         'sub_fields' => [
                             [
                                 'label' => 'Content',
        			'name' => 'contentHTML',
        			'type' => 'wysiwyg',
        			'instructions' => 'Add content to this section.',
                                  'media_upload' => 0,
        			'delay' => 1,
                              ],
                         ]
                     ],
                     [
                         'name' => 'two_columns',
        		'label' => 'Two Columns Content',
                         'sub_fields' => [
                             [
                                  'label' => 'Left Content',
        			'name' => 'left_contentHTML',
        			'type' => 'wysiwyg',
        			'instructions' => 'Add content to this section.',
                                 'media_upload' => 0,
        			'delay' => 1,
                                 'wrapper' =>  [
                                       'width' => '50',
                                ],
                           ],
                           [
                                'label' => 'Right Content',
        			'name' => 'right_contentHTML',
        			'type' => 'wysiwyg',
        			'instructions' => 'Add content to this section.',
        			'media_upload' => 0,
        			'delay' => 1,
                                  'wrapper' =>  [
                                     'width' => '50',
                                  ],
                             ],
                        ]
                      ],
                 ]
            ],
        ]
    ];
}
```

(Sorry for the weird code formatting)

When I add this to my component, I am able to add this component to a page, and the Flexible Content field functions great, as-expected, until I attempt to save the page. Upon save, I get the following error message:

> Warning: Cannot get component: Component 'One_column' is not registered! in [my site's theme location]/lib/ComponentManager.php on line 94

The error message makes me think that the site thinks that the layouts in my Component's Flexible Content field are actual individual components in Flynt and is unable to find a Component folder and files for each layout.

Any thoughts on what might be happening here, and if there's a fix for this?

I've also attached the error stack as a screenshot
![flexible-content-errors](https://user-images.githubusercontent.com/78743889/137536048-620e6346-b3de-4b0d-8b37-b5edd0d785b4.jpg)

**Comment by webmisses** [comment]
Hi there,
is there a solution in the meantime? I also tried to build Nested Flexible Content component - unfortunately it doesn't work....

**Comment by steffenbew** [comment]
@webmisses We haven't planned to implement support for nested flexible content components so far. If that's important to you and you figured out an approach or solution, I would be happy to take a look at it and taking into consideration for future releases!

**Comment by EvanOlsen** [comment]
I'm having the same issue. Adding Flexible Content in ACF via the front end (IE not a Component) triggers the error on the backend. A _non-ideal_ workaround has been to comment out the error response on line 154 of ComponentManager.php "trigger_error("Cannot get component: Component '{$componentName}' is not registered!", E_USER_WARNING);"

I tried add a conditional statement on line 28 of FeatureFlexibleContentExtension.php as recommended above, but the previous line already registers the error as it's attempting to find a Component that's coming from ACF. "$componentPathFull = $componentManager->getComponentDirPath($componentName);"

This would be nice to have a proper work around as turning off errors isn't the best idea.
