### ISSUE TITLE
Get url dist assets from twig

### ISSUE THREAD

**Issue by darksns** [flyntwp/flynt#413]
Hi, is there a method/filter on twig to retrieve the url of an image inside the assets/images folder?
After I run the 'npm run build' command obviously it is appended to the file name '-0123456'
Thank you

**Comment by steffenbew** [comment]
Hi @darksns, yes there is the following function to retrieve the file path of built assets:
```php
use Flynt\Utils\Asset;

$logoPath = Asset::requireUrl('Components/NavigationBurger/Assets/logo.svg')
```
