### ISSUE TITLE
HTML Bloat with subfields

### ISSUE THREAD

**Issue by zethni** [flyntwp/flynt#416]
We have a column structure similar to the one in [this issue](https://github.com/flyntwp/flynt/issues/406), where we have multiple columns with a host of subfields that can be used in any of them. The functionality is working, but we're running into a scale issue - we have up to 6 columns that can use up to 13 subfields. Each time we add a column layout, it's generating the html for all 13 subfields 6 times (within the "clones" div) - for us, this is generating an additional 2Mb of html every time we add a new column layout. Is there a way to minimize how much of that clone html is generated?

**Comment by steffenbew** [comment]
@zethni To my understanding, this is ACF related and we don't apply changes to the backend field rendering.
