### ISSUE TITLE
Will you be interested in a "social sharing" component?

### ISSUE THREAD

**Issue by stefanobartoletti** [flyntwp/flynt#430]
Hi, I'd like to contribute a new component, namely a "social sharing" icons block, something similar to what you can see here at the end of the article:

http://negozianti.sviluppo.host/news/2020/07/01/articolo-di-esempio-1/

Let me know :)

**Comment by steffenbew** [comment]
Hi @stefanobartoletti, I think that could be a nice addition! 
We have a simple [social links](https://flyntwp.com/components/list-social/) component already, but I imagine a social sharing component would be visually integrated differently.

**Comment by stefanobartoletti** [comment]
Thanks :)
Exactly, they will have a different visual integration since they also serve two different purposes.
I'll work on it and open a PR as soon as possible.

**Comment by timohubois** [comment]
See #437.
