### ISSUE TITLE
Issue: npm install errors and warnings

### ISSUE THREAD

**Issue by ogre-yoga** [flyntwp/flynt#431]
- Package node-sass requires downgrade to Node 14 to install properly

- Concerns about number of npm package vulnerabilities as at 2022.03.23 after running `$ npm audit fix`:
`fixed 145 of 213 vulnerabilities in 2309 scanned packages
  44 vulnerabilities required manual review and could not be updated
  9 package updates for 24 vulnerabilities involved breaking changes`

Query: Is this repo/product being actively maintained?

**Comment by ogre-yoga** [comment]
Giving up, Flynt build script failed (assuming PHP8 incompatibility?), but i thank this repo for introducing to me to Timber and Twig!

**Comment by kunsang** [comment]
As mentioned [here](https://github.com/flyntwp/flynt#dependencies), node version @12 is required (you can [use n](https://github.com/tj/n) vor version management)
PHP Version 7.4 or 8.0 works fine, 8.1 doesn't work yet.

**Comment by ogre-yoga** [comment]
Thanks @kunsang , classic case of RTFM. I'll see if i can get it running on next wordpress project, because i think Flynt has some great thinking behind it!
