### ISSUE TITLE
Is there a good way to bulk create posts with components?

### ISSUE THREAD

**Issue by prathamesh-gharat** [flyntwp/flynt#497]
Using something like WP All Importer? : https://www.wpallimport.com/

My concern is that since the ACF fields created inside components are programmatically created I believe that wpallimport will have no idea of their existence.

**Comment by timohubois** [comment]
@prathamesh-gharat thanks for open an issue. It seems that the topic is better placed inside the discussions. 
Feel free to start a new discussion [here](https://github.com/flyntwp/flynt/discussions).

In the meantime I will close this issue.
