### ISSUE TITLE
How to use repo within docker containers - DDEV

### ISSUE THREAD

**Issue by johnquest** [flyntwp/flynt#525]
I manage all of my web dev projects using the docker based DDEV local platform. I can manage everything except accessing the browser outside of my web container upon npm start? Do you have any instructions for how to work with this repository using docker/ddev on Linux?

**Comment by matthewdixon** [comment]
I have the same issue using MAMP PRO (6.8.1) on macOS (14.2).

Firstly, thanks so much for all your amazing work on this project so far! 😍

There's some conflicting info re: `wordpressHost` variable: the variable in [vite.config.js](https://github.com/flyntwp/flynt/blob/master/vite.config.js) includes a port number whereas step 2 in the install instructions doesn't. I've tried both as well as adding `--host` to the dev script: this exposes the server to my network but when I open the supplied URL, ie. my IP with the port number appended, either on the same device or an external one I get a page simply saying 'please open `wordpressHost`' which doesn't work on the external device as it has no way of knowing about it.

Before I go down a proxy rabbit hole it'd be great to know if this is something the team have already got working and if so what mistake I might be making..

**Comment by timohubois** [comment]
@johnquest I used DDEV a lot in the past, but dropped it due lack of clarity what the future of the project will be.

However, with the new Flynt version we introduced Vite and I found a blog post how to setup Vite in combination with DDEV: https://ddev.com/blog/working-with-vite-in-ddev/

Exposing the vite port and adjusting the `vite.config.js` should help to get it working.

**Comment by timohubois** [comment]
@matthewdixon the message to open `wordpressHost’ in development mode is correct.

Have you adjusted the const `wordpressHost’ inside the `vite.config.js’ to your local domain where the WordPress is accessible?

**Comment by johnquest** [comment]
I do have this working in DDEV. But I can only get it work by setting "Host" to the IP address of the ddev web container, and it changes upon restart, so I have to update he IP when the IP of the container changes.

**Comment by matthewdixon** [comment]
Apologies for the late reply, @timohubois - busy busy!

Yea so say I set that const like so - `const wordpressHost = 'http://coolwebsite.local'` - when I access this URL from the same machine all works as expected, but another device on the same network doesn't know about this host. With `--host` added to the serve script like so - `"serve": "vite dev --host"` - my machine's IP is exposed so the external device should be able to access the site at eg. 192.168.1.1:5173, however all this returns is the 'please open http://coolwebsite.local' message..

Have you guys had this up and running your end?

**Comment by timohubois** [comment]
@matthewdixon Great to read from you! It seems that this topic differs from the initial topic of this issue and it would be great if you start a new discussion about exposing into local network while developing. Thanks ✌️
