### ISSUE TITLE
Migration Guide

### ISSUE THREAD

**Issue by cstmth** [flyntwp/flynt#528]
**Is your feature request related to a problem? Please describe.**
I cannot find a migration guide for migrating from v1.4.1 to v2.0.1. I am tasked to upgrade a theme instance which has not been tracked with Git. Otherwise I could have just rebased (or pulled?) onto current master branch et voila. But as it stands, there is no commit history in my theme with changes that have been conducted by prior theme editors. This makes it super hard to unravel which changes were caused by editors and which changes are caused from the 2.0 upgrade.

I might possibly miss something very obvious, but evaluating each and every file by hand before replacing/altering it using the GitHub comparison tool (tag 1.4.1 against master) seems to be a very error-prone solution.

**Describe the solution you'd like**
A migration guide, outlining how to go about upgrading a project would be great for these cases, where automatic upgrades are not supported. If I am missing something, I would be very happy if you could explain how to me how to transition smoothly and securely.

**Comment by timohubois** [comment]
@cstmth in Flynt 2.0 we did a lot of changes like adding a module based islands like javascript architecture, changing the markup, styles and we also moved to [Timber 2](https://timber.github.io/docs/v2/).

Due Flynt is a starter theme for developer and often gets a lot of customizations, it is hard to create or provide a detailed migration guide or automatic updates.

I don't know about your 1.4.1 project, but I also did some updates to Flynt 2 where I started from scratch with a new Flynt 2 installation and migrated component by component. 

But maybe it is enough to just upgrade to Timber 2 for better future-proof PHP compatibility - there is a great [upgrade guide](https://timber.github.io/docs/v2/upgrade-guides/2.0/) and we have done this for many projects based on older Flynt versions.

Hope this helps!
