### ISSUE TITLE
Flynt v2.1: Cannot correctly save ACF Field Groups

### ISSUE THREAD

**Issue by aaronmeder** [flyntwp/flynt#543]
**Describe the bug**
Cannot correctly save or update ACF Fields Groups. Some information gets lost while saving.
Happens with Flynt 2.1, is fine with Flynt 2.0.1 or TwentyTwentyFour theme.

**To Reproduce**
1. Using the ACF ui create a new Field Group, add some fields
2. Save the field group
3. Information like the field type or location rules aren't properly stored.

**Expected behavior**
Field groups can be stored and updated (e.g. changing the type of a field or the Location Rules to another post type) and the changes are reflected after saving.

**Screenshots**
https://www.loom.com/share/5e7aa75fb1ac4872b2256320f9e5f788?sid=34faf71e-8dd9-40da-aaf8-e04c8cff45bc

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: current

**Additional context**
I noticed (when storing the field groups to acf-json in my theme) that the fields look a bit odd (note the "0" key).

Stored with Flynt 2.1 active:
![Screenshot 2024-03-27 at 14 47 38](https://github.com/flyntwp/flynt/assets/5564163/07c148aa-f924-4b25-9a87-92309a7b7198)

Stored with Flynt 2.0.1 active:
![Screenshot 2024-03-27 at 14 49 00](https://github.com/flyntwp/flynt/assets/5564163/0788c054-1125-4cf9-a6a1-360705ffe0df)

**Comment by timohubois** [comment]
Hey @aaronmeder, 

many thanks for figure this out! 

Did a short test and can confirm the behavior. 

As quickfix, you can try to add 'acf-field-group' inside the [theContentFix.php](https://github.com/flyntwp/flynt/blob/055e25c76b4a6bb01788e53c9efa84be9023b141/inc/theContentFix.php#L8):

```
    if (
        in_array(
            $postArr['post_type'],
            [
                'revision',
                'nav_menu_item',
                'attachment',
                'customize_changeset',
                'custom_css',
                'acf-field-group'
            ]
        )
    ) {
        return $data;
    }
```
Will investigate this issue deeper asap and commit the changes to the master branch.

Let me know if this works for you?

**Comment by aaronmeder** [comment]
Hmm not fully: it seems to fix assigning Location rules, but it's still not saving field types for me.

**Comment by aaronmeder** [comment]
@timohubois Hmm not fully: it seems to fix assigning Location rules, but it's still not saving field types for me.

**Comment by aaronmeder** [comment]
@timohubois Ah looks like I also need to add the acf-field post type:

```php
if (
        in_array(
            $postArr['post_type'],
            [
                'revision',
                'nav_menu_item',
                'attachment',
                'customize_changeset',
                'custom_css',
                'acf-field-group',
                'acf-field'
            ]
        )
    ) {
        return $data;
    }

```

It seems to work like that. Should it be fine like this?

**Comment by timohubois** [comment]
@aaronmeder can you try to add 'acf-field' as well: 

  ```
  if (
        in_array(
            $postArr['post_type'],
            [
                'revision',
                'nav_menu_item',
                'attachment',
                'customize_changeset',
                'custom_css',
                'acf-field-group',
                'acf-field'
            ]
        )
    ) {
        return $data;
    }
```

**Comment by timohubois** [comment]
> @timohubois Ah looks like I also need to add the acf-field post type:
> 
> ```
> if (
>         in_array(
>             $postArr['post_type'],
>             [
>                 'revision',
>                 'nav_menu_item',
>                 'attachment',
>                 'customize_changeset',
>                 'custom_css',
>                 'acf-field-group',
>                 'acf-field'
>             ]
>         )
>     ) {
>         return $data;
>     }
> ```
> 
> It seems to work like that. Should it be fine like this?

You was 1 minute faster 😅

This should work, but maybe there are other edge cases. Will dive deeper it this evening ✌️

**Comment by timohubois** [comment]
@aaronmeder did some tests and excluded all acf related post types now, you can find the WIP branch here:
https://github.com/flyntwp/flynt/tree/543-flynt-v21-cannot-correctly-save-acf-field-groups

Let me know if the changes work for you?

**Comment by aaronmeder** [comment]
@timohubois Works great for me!
