### ISSUE TITLE
CDN emojis not available

### ISSUE THREAD

**Issue by cafesk8** [flyntwp/flynt#560]
Emojis in premium components loaded via CDN don't work - see screenshot [here](https://i.imgur.com/VpiHZnr.png) and linked URLS - for example [this one](https://cdn.jsdelivr.net/gh/jdecked/twemoji@15.0.3/assets/1f3c6.svg)

**Comment by timohubois** [comment]
@cafesk8 kindly want to ask if you found the time test the suggested solution?
