### ISSUE TITLE
WordPress 6.7 Translation Issue and Workaround

### ISSUE THREAD

**Issue by TheChriZZoW** [flyntwp/flynt#578]
WordPress 6.7 introduced a change in translation handling that currently prevents themes like Flynt from loading translations from their local language folders. This issue is known and will be hopefully fixed in WordPress 6.7.1.

If you've already updated to 6.7 and don't want to wait for the fix, you can manually adjust the translation loading function in Flynt's `functions.php` from

```
add_action('after_setup_theme', function (): void {
    // Make theme available for translation.
    // Translations can be filed in the /languages/ directory.
    load_theme_textdomain('flynt', get_template_directory() . '/languages');
});
```

to

```
add_action('init', function (): void {
    // Make theme available for translation.
    // Translations can be filed in the /languages/ directory.

    // First, try loading translations from the theme's local languages folder
    load_theme_textdomain('flynt', get_template_directory() . '/languages');

    // Then, fallback to the centralized languages folder
    load_theme_textdomain('flynt', WP_LANG_DIR . '/themes');
});
```

This will instruct WordPress to first search for translations in the local language folder of the Flynt theme and then to look in the global language directory `wp-content/languages/themes/`.

Additionally, you'll need to copy the Flynt language files (`*.mo` and `*.po`) from the theme's `/languages/` folder to the following directory:

```
wp-content/languages/themes/flynt-{locale}.mo
wp-content/languages/themes/flynt-{locale}.po
```

Note: While this workaround resolves the immediate translation issue, you may still encounter a PHP notice in the debug log. This will be hopefully fixed in the upcoming WordPress 6.7.1 update.

**Comment by timohubois** [comment]
@TheChriZZoW Many thanks for the PR! I haven’t started deeper testing yet, but I did some research today and came across this ticket: https://core.trac.wordpress.org/ticket/62337.

Have you seen this as well and tried the solutions discussed there?

**Comment by timohubois** [comment]
@TheChriZZoW I just saw that the release of WordPress 6.7.1 is planned for November 21, 2024. It includes their ticket #62337: https://make.wordpress.org/core/2024/11/19/wordpress-6-7-1-release-schedule/

**Comment by TheChriZZoW** [comment]
@timohubois After updating to WordPress 6.7.1, the translations work as expected again. The `after_setup_theme` action in the `functions.php` file of Flynt no longer needs to be modified to properly load translation files from the Theme folder. The issue has been resolved for me, and I'm back to using the following action:

```
add_action('after_setup_theme', function (): void {
    // Make theme available for translation.
    // Translations can be filed in the /languages/ directory.
    load_theme_textdomain('flynt', get_template_directory() . '/languages');
});
```
